# Generated by Django 4.2.7 on 2025-06-11 22:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analyzer", "0003_review_rating_review_sentiment_review_suggestion"),
    ]

    operations = [
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
            ],
        ),
    ]
